import "./globals.css";
import Header from "./components/Header/Header";

import { UserProvider } from "./context/UserContext/UserContext";

export const metadata = {
  title: "MyNoteApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider >
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
    </UserProvider>
  );
}
